apiVersion: v1
kind: Service
metadata:
  name: devops-project-svc
spec:
  type: LoadBalancer
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: 80         # external port
      targetPort: 5001 # Flask container port
