replicaCount: 2
fullnameOverride: flask-app-deployment

image:
  repository: eniselkunch/devops-project
  tag: ""      # default, will override dynamically
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

containerPort: 5001
