name: CI/CD Pipeline

env:
  IMAGE_TAG: eniselkunch/devops-project:${{ github.sha }}
on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint (Flake8)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # - name: Install flake8
      #   run: pip install flake8

      # - name: Run flake8
      #   run: flake8 src

# after the build is done 
  # test:
    # name: Unit Tests (Pytest)
    # runs-on: ubuntu-latest
    # needs: lint

    # steps:
    #   - uses: actions/checkout@v4

    #   - name: Set up Python
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: 3.11

    #   - name: Install dependencies
    #     run: |
    #       pip install -r requirements.txt
    #       pip install pytest

    #   - name: Run tests
    #     run: pytest


  security:
    name: Security Scan (Bandit)
    runs-on: ubuntu-latest
    #needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r src


  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: security

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          echo "Building image with tag $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      #- name: Deploy to Kubernetes
        #run: kubectl apply --validate=false -f k8s/deployment.yaml
    
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Authenticate to GCP using the service account JSON
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Install gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cybernetic-tide-474909-n0
          version: 'latest'
          install_components: gke-gcloud-auth-plugin


      # Get credentials for your GKE cluster
      - name: Get GKE credentials
        run: |
           gcloud container clusters get-credentials devopsproject-cluster-1 --zone us-central1

      # Deploy to Kubernetes
      - name: Deploy to GKE
        run: |
          helm upgrade --install flask-app ./flask-app --namespace default --set image.tag=$IMAGE_TAG
          

         



